version: "3"
services:
    btc-real-time-etl:
        build:
            context: .
            dockerfile: ./extract_real_time_upbit_candles.Dockerfile
        container_name: btc_candle_real_time_etl
        environment:
            MARKET: "KRW-BTC"

    eth-real-time-etl:
        build:
            context: .
            dockerfile: ./extract_real_time_upbit_candles.Dockerfile
        container_name: eth_candle_real_time_etl
        environment:
            MARKET: "KRW-ETH"

